# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        type: choice
        description: Choose test to run
        options: 
        - All
        - Tickets Creating
        - Tickets Updating
        - Tickets Invoice
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Detox Run
      run: |
        if [[ ${{ github.event_name }} != 'workflow_dispatch' ]]; then
          test_type="TEST"
        else
          test_type=${{inputs.env}}
        fi
        echo "Hello ${{ inputs.name }}"
        echo $test_type
